### ISSUE TITLE
Add "just the dot" variation

### ISSUE THREAD

**Issue by kytta** [AnWeber/dot-icons#1]
Hi, loving the theme! I enjoy the minimalism, but files having that generic “file” icon in the background are still a bit too distracting for me. Would you be up to add another variation of the theme, namely "just the dot"? So it would look something like this (mockup):

<img width="229" alt="Screenshot" src="https://github.com/user-attachments/assets/5eeae76d-0753-4744-ad55-dca127ed93d0">

**Comment by AnWeber** [comment]
Yeah. Can you provide a PR?

**Comment by kytta** [comment]
I'll try to find the time 😁

**Comment by AnWeber** [comment]
I once created a version with “just dots”. See if you like it that way.

**Comment by kytta** [comment]
Perfect! Exactly how I imagined it, thank you!
